bookers/config/routes.rb
Rails.application.routes.draw do
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # get 'top' => 'homes#top'
  root to: 'books#top'
  get 'top' => 'books#top'
  resources :books
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
      render :index
    end
  end

  def new
    # @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully updated."
    redirect_to books_path
  end


  # ストロングパラメータ
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    # @homes = homes.all
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<div class ="edit">
<h2>Editing Book</h2>
<%= form_with model:@book, local:true do |f| %>
<% if @book.errors.any? %>
  <div class="editerrormes">
    <h4><%= @book.errors.count %>error prohibited this book from being saved:</h4>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
</textarea>
  </div>

  <div class="actions">
     <%= f.submit 'Update Book' %>
  </div>
  <% end %>
  </div>
</div>
  
<p class ="editlink">
<%= link_to "Show", book_path %>
|
<%= link_to "Back", books_path %>
</p>

bookers/app/views/books/index.html.erb
<div class ="index">
  
  <div class ="indexbox">
  <p class ="notice"><%= flash[:notice] %></p>
 

<h1>Books</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <!--投稿データ-->
      <% @books.each do |book| %>
      
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?"  %></td>
        </tr>
       <% end %> 
  </tbody>
</table>


<h3 class ="formtitle">New book</h3>
<!--エラーメッセージ-->
<!--投稿フォーム-->

<%= form_with model:@book, local:true do |f| %>

　<% if @book.errors.any? %>
  <div class="errormes">
    <h4><%= @book.errors.count %>error prohibited this book from being saved:</h4>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
　<% end %>

  <div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
     <%= f.submit 'Create Book' %>
  </div>
  <% end %>
  </div>
</div>

bookers/app/views/books/show.html.erb
<div class ="show">
<p class ="notice"><%= flash[:notice] %></p>

<p class ="showtitle">
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

</div>


<p class ="start">
<%= link_to "Edit", edit_book_path %>
|
<%= link_to "Back", books_path %>
</p>

bookers/app/views/books/top.html.erb
<div class ="top">
  
<h1>ようこそ Bookersへ！</h1>
<p class ="hometop"><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p class ="hometop">印象を共有し交換することが出来ます</p>

<p class ="start">
<%= link_to "start", books_path %>
</p>

</div>

bookers/app/views/homes/top.html.erb
<div class ="top">
  
<h1>ようこそ Bookersへ！</h1>
<p class ="hometop"><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p class ="hometop">印象を共有し交換することが出来ます</p>

</div>
  
<span>
<%= link_to start, "/books/new" %>
</span>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>